let definitions = {
    'absolute value' : 'The distance of a number from zero; the positive value of a number.',
    'acute angle' : 'A positive angle measuring less than 90 degrees.',
    'acute triangle' : 'A triangle each of whose angles measures less than 90 degrees.',
    'additive identity' : 'The number zero is called the additive identity because the sum of zero and any number is that number.',
    'additive inverse' : 'The additive inverse of any number x is the number that gives zero when added to x. The additive inverse of 5 is -5.',
    'adjacent angles' : 'Two angles that share both a side and a vertex.',
    'angle' : 'The union of two rays with a common endpoint, called the vertex.',
    'arc' : 'A portion of the circumference of a circle.',
    'area' : 'The number of square units that covers a shape or figure.',
    'associative property of addition' : '(a + b) + c = a + (b + c)',
    'associative property of multiplication' : '(a x b) x c = a x (b x c)',
    'average' : 'A number that represents the characteristics of a data set.',
    'axis of symmetry' : 'A line that passes through a figure in such a way that the part of the figure on one side of the line is a mirror reflection of the part on the other side of the line.',
    'base' : 'The bottom of a plane figure or three-dimensional figure.',
    'bisect' : 'To divide into two congruent parts.',
    'Box and whisker plot' : 'A type of data plot that displays the quartiles and range of a data set.',
    'Cartesian coordinates' : 'A system in which points on a plane are identified by an ordered pair of numbers, representing the distances to two or three perpendicular axes.',
    'central angle' : 'An angle that has its vertex at the center of a circle.',
    'chord' : 'A line segment that connects two points on a curve.',
    'circle' : 'The set of points in a plane that are a fixed distance from a given point, called the center.',
    'circumference' : 'The distance around a circle.',
    'coefficient' : 'A constant that multiplies a variable.',
    'collinear' : 'Points are collinear if they lie on the same line.',
    'combination' : 'A selection in which order is not important.',
    'common factor' : 'common factor',
    'common multiple' : 'A multiple of two or more numbers.',
    'commutative property of addition' : 'a + b = b + a.',
    'commutative property of multiplication' : 'a*b = b*a.',
    'complementary angles' : 'Two angles whose sum is 90 degrees.',
    'composite number' : 'A natural number that is not prime.',
    'cone' : 'A three-dimensional figure with one vertex and a circular base.',
    'congruent' : 'Figures or angles that have the same size and shape.',
    'constant' : 'A value that does not change.',
    'coordinate plane' : 'The plane determined by a horizontal number line, called the x-axis, and a vertical number line, called the y-axis, intersecting at a point called the origin. Each point in the coordinate plane can be specified by an ordered pair of numbers.',
    'coplanar' : 'Points that lie within the same plane.',
    'counting numbers' : 'The natural numbers, or the numbers used to count.',
    'counting principle' : 'If a first event has n outcomes and a second event has m outcomes, then the first event followed by the second event has n times m outcomes.',
    'cross product' : 'A product found by multiplying the numerator of one fraction by the denominator of another fraction and the denominator of the first fraction by the numerator of the second.',
    'cube' : 'A solid figure with six square faces.',
    'cylinder' : 'A three-dimensional figure having two parallel bases that are congruent circles.',
    'data' : 'Information that is gathered.',
    'decimal number' : 'The numbers in the base 10 number system, having one or more places to the right of a decimal point.',
    'degree' : 'A unit of measure of an angle.',
    'denominator' : 'The bottom part of a fraction.',
    'dependent events' : 'Two events in which the outcome of the second is influenced by the outcome of the first.',
    'diagonal' : 'The line segment connecting two nonadjacent vertices in a polygon.',
    'diameter' : 'The line segment joining two points on a circle and passing through the center of the circle.',
    'difference' : 'The result of subtracting two numbers.',
    'digit' : 'The ten symbols, 0, 1, 2, 3, 4, 5, 6, 7, 8, and 9. The number 215 has three digits: 2, 1, and 5.',
    'distributive property' : 'a(b + c) = ab + ac',
    'dividend' : 'In a / b = c, a is the dividend.',
    'divisor' : 'In a / b = c, b is the divisor.',
    'ellipse' : 'The set of all points in a plane such that the sum of the distances to two fixed points is a constant.',
    'equation' : 'A mathematical statement that says that two expressions have the same value; any number sentence with an =.',
    'equilateral triangle' : 'A triangle that has three equal sides.',
    'equivalent equations' : 'Two equations whose solutions are the same.',
    'equivalent fractions' : 'Fractions that reduce to the same number.',
    'error of measurement' : 'The difference between an approximate measurement and the actual measure taken.',
    'evaluate' : 'To substitute number values into an expression.',
    'even number' : 'A natural number that is divisible by 2.',
    'event' : 'In probability, a set of outcomes.',
    'exponent' : 'A number that indicates the operation of repeated multiplication.',
    'factor' : 'One of two or more expressions that are multiplied together to get a product.',
    'factoring' : 'To break a number into its factors.',
    'face' : 'A flat surface of a three-dimensional figure.',
    'formula' : 'A equation that states a rule or a fact.',
    'fraction' : 'A number used to name a part of a group or a whole. The number below the bar is the denominator, and the number above the bar is the numerator.',
    'frequency' : 'The number of times a particular item appears in a data set.',
    'frequency table' : 'A data listing which also lists the frequencies of the data.',
    'graph' : 'A type of drawing used to represent data.',
    'greatest common factor (GCF)' : 'The largest number that divides two or more numbers evenly.',
    'horizontal' : 'A line with zero slope.',
    'hypotenuse' : 'The side opposite the right angle in a right triangle.',
    'identity property of addition' : 'The sum of any number and 0 is that number.',
    'identity property of multiplication' : 'The product of 1 and any number is that number.',
    'improper fraction' : 'A fraction with a numerator that is greater than the denominator.',
    'independent events' : 'Two events in which the outcome of the second is not affected by the outcome of the first.',
    'inequality' : 'A mathematical expression which shows that two quantities are not equal.',
    'infinity' : 'A limitless quantity.',
    'inscribed angle' : 'An angle placed inside a circle with its vertex on the circle and whose sides contain chords of the circle.',
    'inscribed polygon' : 'A polygon placed inside a circle so that each vertex of the polygon touches the circle.',
    'integers' : 'The set of numbers containing zero, the natural numbers, and all the negatives of the natural numbers.',
    'intercept' : 'The x-intercept of a line or curve is the point where it crosses the x-axis, and the y- intercept of a line or curve is the point where it crosses the y-axis.',
    'intercepted arc' : 'The arc of a circle within an inscribed angle.',
    'interpolation' : 'A method for estimating values that lie between two known values.',
    'intersecting lines' : 'Lines that have one and only one point in common.',
    'inverse' : 'Opposite. -5 is the additive inverse of 5, because their sum is zero. 1/3 is the multiplicative inverse of 3, because their product is 1.',
    'inverse operations' : 'Two operations that have the opposite effect, such as addition and subtraction.',
    'irrational number' : 'A number that cannot be expressed as the ratio of two integers.',
    'isosceles triangle' : 'A triangle with at least two equal sides.',
    'least common denominator' : 'The smallest multiple of the denominators of two or more fractions.',
    'least common multiple (LCM)' : 'The smallest nonzero number that is a multiple of two or more numbers.',
    'like fractions' : 'Fractions that have the same denominator.',
    'line' : 'A straight set of points that extends into infinity in both directions.',
    'line of symmetry' : 'Line that divides a geometric figure into two congruent portions.',
    'line segment' : 'Two points on a line, and all the points between those two points.',
    'locus' : 'A path of points.',
    'logic' : 'The study of sound reasoning.',
    'lowest terms' : 'Simplest form; when the GCF of the numerator and the denominator of a fraction is 1.',
    'mean' : 'In a data set, the sum of all the data points, divided by the number of data points; average.',
    'median' : 'The middle number in a data set when the data are put in order; a type of average.',
    'midpoint' : 'A point on a line segment that divides the segment into two congruent segments.',
    'mixed number' : 'A number written as a whole number and a fraction.',
    'mode' : 'A type of average; the number (or numbers) that occurs most frequently in a set of data.',
    'multiple' : 'A multiple of a number is the product of that number and any other whole number. Zero is a multiple of every number.',
    'multiplicative identity' : 'The number 1 is the multiplicative identity because multiplying 1 times any number gives that number.',
    'multiplicative inverse' : 'The reciprocal of a number.',
    'mutually exclusive events' : 'Two or more events that cannot occur at the same time.',
    'natural numbers' : 'The counting numbers.',
    'negative number' : 'A real number that is less than zero.',
    'normal' : 'Perpendicular.',
    'number line' : 'A line on which every point represents a real number.',
    'numerator' : 'The top part of a fraction.',
    'obtuse angle' : 'An angle whose measure is greater than 90 degrees.',
    'obtuse triangle' : 'A triangle with an obtuse angle.',
    'octagon' : 'A polygon with 8 sides.',
    'odd number' : 'A whole number that is not divisible by 2.',
    'operation' : 'Addition, subtraction, multiplication, and division are the basic arithmetic operations.',
    'opposites' : 'Two numbers that lie the same distance from 0 on the number line but in opposite directions.',
    'ordered pair' : 'Set of two numbers in which the order has an agreed-upon meaning, such as the Cartesian coordinates (x, y), where the first coordinate represents the horizontal position, and the second coordinate represents the vertical position.',
    'origin' : 'The point (0, 0) on a coordinate plane, where the x-axis and the y-axis intersect.',
    'outcome' : 'In probability, a possible result of an experiment.',
    'parallel' : 'Two lines are parallel if they are in the same plane and never intersect.',
    'parallelogram' : 'A quadrilateral with opposite sides parallel.',
    'pentagon' : 'A five-sided polygon.',
    'percent' : 'A fraction, or ratio, in which the denominator is assumed to be 100. The symbol % is used for percent.',
    'perimeter' : 'The sum of the lengths of the sides of a polygon.',
    'permutation' : 'A way to arrange things in which order is important.',
    'perpendicular' : 'Two lines are perpendicular if the angle between them is 90 degrees.',
    'pi' : 'The ratio of the circumference of a circle to its diameter.',
    'plane' : 'A flat surface that stretches into infinity.',
    'point' : 'A location in a plane or in space, having no dimensions.',
    'polygon' : 'A closed plane figure made up of several line segments that are joined together.',
    'polyhedron' : 'A three-dimensional solid that is bounded by plane polygons.',
    'positive number' : 'A real number greater than zero.',
    'power' : 'A number that indicates the operation of repeated multiplication.',
    'prime number' : 'A number whose only factors are itself and 1.',
    'probability' : 'For an experiment, the total number of successful events divided by the total number of possible events.',
    'product' : 'The result of two numbers being multiplied together.',
    'proper fraction' : 'A fraction whose numerator is less than its denominator.',
    'proportion' : 'An equation of fractions in the form: a/b = c/d',
    'protractor' : 'A device for measuring angles.',
    'pyramid' : 'A three-dimensional figure that has a polygon for its base and whose faces are triangles having a common vertex.',
    'Pythagorean Theorem' : 'The theorem that relates the three sides of a right triangle: a^2 + b^2 = c^2',
    'quadrant' : 'One of the quarters of the plane of the Cartesian coordinate system',
    'quadrilateral' : 'A polygon with 4 sides.',
    'quotient' : 'The answer to a division problem.',
    'radius' : 'The distance from the center to a point on a circle; the line segment from the center to a point on a circle.',
    'range' : 'In statistics, the difference between the largest and the smallest numbers in a data set.',
    'rate' : 'A ratio that compares different kinds of units.',
    'ratio' : 'A pair of numbers that compares different types of units.',
    'rational number' : 'A number that can be expressed as the ratio of two integers.',
    'ray' : 'part of a line, with one endpoint, and extending to infinity in one direction.',
    'real numbers' : 'The combined set of rational numbers and irrational numbers.',
    'reciprocal' : 'The number which, when multiplied times a particular fraction, gives a result of 1.',
    'rectangle' : 'A quadrilateral with four 90-degree angles.',
    'reflection' : 'A transformation resulting from a flip.',
    'regular polygon' : 'A polygon in which all the angles are equal and all of the sides are equal.',
    'repeating decimal' : 'A decimal in which the digits endlessly repeat a pattern.',
    'rhombus' : 'A parallelogram with four equal sides.',
    'right angle' : 'An angle whose measure is 90 degrees.',
    'right triangle' : 'A triangle that contains a right angle.',
    'root' : 'The root of an equation is the same as the solution to the equation.',
    'rotation' : 'A transformation in which a figure is rotated through a given angle, about a point.',
    'sample space' : 'For an experiment, the sample space includes all the possible outcomes.',
    'Scale drawing' : 'A drawing that is a reduction or enlargement of the original.',
    'scalene triangle' : 'A triangle with three unequal sides.',
    'scattergram' : 'A graph with points plotted on a coordinate plane.',
    'scientific notation' : 'A method for writing extremely large or small numbers compactly in which the number is shown as the product of two factors.',
    'set' : 'A well-defined group of objects.',
    'similar' : 'Two polygons are similar if their corresponding sides are proportional.',
    'simplifying' : 'Reducing to lowest terms.',
    'skew lines' : 'Lines that are not in the same plane and that do not intersect.',
    'slope' : 'The steepness of a line expressed as a ratio, using any two points on the line.',
    'solution' : 'The value of a variable that makes an equation true.',
    'sphere' : 'A three-dimensional figure with all points in space a fixed distance from a given point, called the center.',
    'square' : 'A quadrilateral with four equal sides and four 90 degree angles.',
    'square root' : 'The square root of x is the number that, when multiplied by itself, gives the number, x.',
    'statistics' : 'The science of collecting, organizing, and analyzing data.',
    'stem and leaf plot' : 'A technique for organizing data for comparison.',
    'straight angle' : 'An angle that measures 180 degrees.',
    'supplementary angles' : 'Two angles are supplementary if their sum is 180 degrees.',
    'surface area' : 'For a three-dimensional figure, the sum of the areas of all the faces.',
    'terminating decimal' : 'A fraction whose decimal representation contains a finite number of digits.',
    'translation' : 'A transformation, or change in position, resulting from a slide with no turn.',
    'transformation' : 'A change in the position, shape, or size of a geometric figure.',
    'transversal' : 'A line that intersects two other lines.',
    'trapezoid' : 'A quadrilateral that has exactly two sides parallel.',
    'tree diagram' : 'A diagram that shows outcomes of an experiment.',
    'triangle' : 'A three-sided polygon.',
    'unit price' : 'Price per unit of measure. >',
    'variable' : 'A letter used to represent a number value in an expression or an equation.',
    'vertex' : 'The point on an angle where the two sides intersect.',
    'vertical angles' : 'A pair of opposite angles that is formed by intersecting lines.',
    'volume' : 'A measurement of space, or capacity.',
    'whole numbers' : 'The set of numbers that includes zero and all of the natural numbers.',
    'x-axis' : 'The horizontal axis in a Cartesian coordinate plane.',
    'x-intercept' : 'The value of x at the point where a line or curve crosses the x-axis.',
    'y-axis' : 'The vertical axis in a Cartesian coordinate system.',
    'y-intercept' : 'The value of y at the point where a curve crosses the y-axis.',
    'zero' : 'The additive identity; the number that, when added to another number n, gives n.',
    'zero property of multiplication' : 'The product of zero and any number is zero.'
}

function startFunction(){
    for (let i=0; i<Object.keys(definitions).length; i++){
        const parent= document.querySelector('.' + Object.keys(definitions)[i][0].toUpperCase());
        const tag = document.createElement('button');
        tag.innerHTML = Object.keys(definitions)[i];
        tag.onclick = function(){
            document.querySelector('.word').innerHTML = Object.keys(definitions)[i];
            document.querySelector('.definition').innerHTML = Object.values(definitions)[i];
        };
        parent.appendChild(tag)
    }   
}

